# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    firebase_test_lab_ios_xctest(
      app_path:"build_products.zip",
      gcp_project: "streamer-1b3b1", # Your Google Cloud project name
      oauth_key_file_path: "streamer.json",
      timeout_sec: "600",
      async: true,
      devices: [ # Device(s) to run tests on
        {
          ios_model_id: "iphone13pro",        # Device model ID, see gcloud command above
          ios_version_id: "15.2",         # iOS version ID, see gcloud command above
          locale: "en_US",                # Optional: default to en_US if not set
          orientation: "portrait",         # Optional: default to portrait if not set
        }
      ],
    )
  end
end
