default_platform(:ios)

platform :ios do
	desc "Description of what the lane does"
	lane :test do
		begin
			firebase_test_lab_ios_xctest(
				app_path:"build_products.zip",
				gcp_project: "streamer-1b3b1", 
				oauth_key_file_path: "streamer.json",
				timeout_sec: "1500",
				async: true,
				devices: [ 
					{
						ios_model_id: "iphone14pro",        
						ios_version_id: "16.6",         
						locale: "en_US",                
						orientation: "portrait",         
					}
				],
			)
		rescue => ex
			UI.error("Something went wrong: #{ex}")
		end
		begin
			firebase_test_lab_ios_xctest(
				app_path:"build_products.zip",
				gcp_project: "atom---movie-tickets", 
				oauth_key_file_path: "streamer1.json",
				timeout_sec: "1500",
				async: true,
				devices: [ 
					{
						ios_model_id: "iphone12pro",        
						ios_version_id: "14.8",         
						locale: "en_US",                
						orientation: "portrait",         
					}
				],
			)
		rescue => ex
			UI.error("Something went wrong: #{ex}")
		end
		begin
			firebase_test_lab_ios_xctest(
				app_path:"build_products.zip",
				gcp_project: "streamer-broadcaster", 
				oauth_key_file_path: "streamer2.json",
				timeout_sec: "1500",
				async: true,
				devices: [ 
					{
						ios_model_id: "iphone12pro",        
						ios_version_id: "14.8",         
						locale: "en_US",                
						orientation: "portrait",         
					}
				],
			)
		rescue => ex
			UI.error("Something went wrong: #{ex}")
		end
		begin
			firebase_test_lab_ios_xctest(
				app_path:"build_products.zip",
				gcp_project: "testproject-7ba62", 
				oauth_key_file_path: "streamer3.json",
				timeout_sec: "1500",
				async: true,
				devices: [ 
					{
						ios_model_id: "iphone12pro",        
						ios_version_id: "14.8",         
						locale: "en_US",                
						orientation: "portrait",         
					}
				],
			)
		rescue => ex
			UI.error("Something went wrong: #{ex}")
		end
		begin
			firebase_test_lab_ios_xctest(
				app_path:"build_products.zip",
				gcp_project: "moslsl1-efa50", 
				oauth_key_file_path: "streamer4.json",
				timeout_sec: "1500",
				async: true,
				devices: [ 
					{
						ios_model_id: "iphone12pro",        
						ios_version_id: "14.8",         
						locale: "en_US",                
						orientation: "portrait",         
					}
				],
			)
		rescue => ex
			UI.error("Something went wrong: #{ex}")
		end
		begin
			firebase_test_lab_ios_xctest(
				app_path:"build_products.zip",
				gcp_project: "ramdan-91652", 
				oauth_key_file_path: "streamer5.json",
				timeout_sec: "1500",
				async: true,
				devices: [ 
					{
						ios_model_id: "iphone11pro",        
						ios_version_id: "14.7",         
						locale: "en_US",                
						orientation: "portrait",         
					}
				],
			)
		rescue => ex
			UI.error("Something went wrong: #{ex}")
		end

	end
