name: AppCenter
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "build_products_clicks.zip"

      - name: Unzip
        run:
          unzip build_products_clicks.zip

      - name: Install AppCenter
        run: |
          npm install -g appcenter-cli@2.10.10

      - name: run any App Center CLI command
        run: |
          appcenter test run xcuitest --async --app "${{secrets.APP_CENTER_USER_APP}}" --devices "${{secrets.APP_CENTER_USER_DEVICES}}" --test-series "master" --locale "en_US" --build-dir build_products/Release-iphoneos --token ${{secrets.APP_CENTER_TOKEN}}
