name: Firebase
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Purge Workflow History
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 1

      - name: Check repo
        uses: actions/checkout@master
      
      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "build_products.zip"

      - name: Bundle
        run: bundle install

      - name: print secrets
        run: |
            echo $FIREBASE_AUTH >> streamer.json
        shell: bash
        env:
          FIREBASE_AUTH : ${{secrets.FIREBASE_AUTH}}

      - name: Test
        run: bundle exec fastlane test
