name: Firebase
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Purge Workflow History
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 1

      - name: Check repo
        uses: actions/checkout@master
      
      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "build_products.zip"

      - name: Bundle
        run: bundle install

      - name: print secrets
        run: |
            echo $FIREBASE_AUTH >> streamer.json
            echo $FIREBASE_AUTH_1 >> streamer1.json
            echo $FIREBASE_AUTH_2 >> streamer2.json
            echo $FIREBASE_AUTH_3 >> streamer3.json
            echo $FIREBASE_AUTH_4 >> streamer4.json
            echo $FIREBASE_AUTH_5 >> streamer5.json

        shell: bash
        env:
          FIREBASE_AUTH : ${{secrets.FIREBASE_AUTH}}
          FIREBASE_AUTH_1 : ${{secrets.FIREBASE_AUTH_1}}
          FIREBASE_AUTH_2 : ${{secrets.FIREBASE_AUTH_2}}
          FIREBASE_AUTH_3 : ${{secrets.FIREBASE_AUTH_3}}
          FIREBASE_AUTH_4 : ${{secrets.FIREBASE_AUTH_4}}
          FIREBASE_AUTH_5 : ${{secrets.FIREBASE_AUTH_5}}

      - name: Test
        run: bundle exec fastlane test
