name: Release
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "version number:"
        required: true
        default: ""
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
   
      - name: install dpkg
        run: brew install dpkg

      - name: install permasigner
        run: pip3 install -U permasigner --break-system-packages --ignore-installed
        
      - name: install create-dmg
        run: brew install create-dmg
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          token: ${{ secrets.REPOSITORY_GITHUB_TOKEN }}

      - name: Cache packages
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: |
            packages_cache/artifacts
            packages_cache/checkouts
            packages_cache/workspace_state.json
          key: ${{ runner.os }}-packages-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-packages-

      - name: Bundle
        run: bundle install

      - name: Build and release
        run: bundle exec fastlane release_local version_number:${{github.event.inputs.version_number}}
        env:
          HAS_PACKAGES_CACHE_HIT: ${{ steps.packages-cache.outputs.cache-hit == 'true' }}

      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: v${{github.event.inputs.version_number}} release
          access_token: ${{ secrets.REPOSITORY_GITHUB_TOKEN }}
          empty: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Release v${{github.event.inputs.version_number}}"
          prerelease: true
          name: v${{github.event.inputs.version_number}}-prerelease-${{ github.run_id }}
          tag_name: v${{github.event.inputs.version_number}}-prerelease-${{ github.run_id }}
          files: |
            Streamer-iOS.ipa
            Streamer-visionOS.ipa
            Streamer-tvOS.ipa
            Streamer-mac.dmg
            Streamer-iOS.deb
            Streamer-tvOS.deb
