name: UI Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
    
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Purge Workflow History
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0

      - name: Check repo
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPOSITORY}}
          token: ${{ secrets.TOKEN }}
      - uses: pat-s/always-upload-cache@v3.0.1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: pat-s/always-upload-cache@v3.0.1
        with:
          path: build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Bundle
        run: bundle install
      - name: Test
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
        run: bundle exec fastlane test
      - uses: kishikawakatsumi/xcresulttool@v1.5.0
        with:
          show-passed-tests: false
          path: fastlane/test_output/StreamerUITests.xcresult
          if: always()
